[project]
name = "product"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luís Rodrigues", email = "luis.rodrigues@criticalsoftware.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langgraph",
    "langchain-ollama",
]

[project.scripts]
product = "product:main"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
